### ISSUE TITLE
opp doesn't reset the main branch after creating a PR

### ISSUE THREAD

**Issue by gabrielreid** [cupcicm/opp#101]
I seem to remember using a competing product (that was possibly implemented in Python), and it would reset the local branch after creating a PR.

For example, if you could add a commit on your local copy of the `main` branch (which was the same as `origin/main`), then run `opp pr`, and this would create the PR branch _and_ reset your local main branch to `origin/main`.

Is the lack of this behavior in opp intentional?

With opp, I find that I need to always manually reset my `main` branch after running `opp pr` so that I can start working on a new, unrelated feature.

**Comment by cupcicm** [comment]
@epot convinced me to implement something in opp that didn't exist in that tool : dependent PRs.
So now, on main, you can git commit 3 times, then send the first two commits for review in a pr/1 (`opp pr HEAD^`) and then you can push the last commit as a dependent pr (`opp pr`). It will create a PR that "contains" only that commit (e.g. a pr that points to pr/1 so that the reviewer reviews only that commit) and opp will take care that you merge in the right order.
This meant I chose to not make the default what you're saying yeah.  Hmmm. 
What I didn't like is this discrepancy:
- if I do `opp pr HEAD^` I can't reset main. I could be clever and "remove" everything except the last commit but there could be conflicts.
- if I do `opp pr HEAD` then main is reset. Weird no ?

**Comment by cupcicm** [comment]
(note that, like for git, if you have a `opp-gabriel-pr.sh` in your path, that does exactly what you want (for example I wrote a `opp-detach.sh` that does this
```#!/bin/bash
mainbranch=$(git rev-parse --abbrev-ref origin/HEAD | sed s#origin/##)
opp pr --interactive --base $mainbranch```
that I use a lot. So maybe it's a way to get exactly what you're used to)

**Comment by epot** [comment]
Note that if you do: `opp pr --checkout` then it should to the same as the competing product you are used to.

**Comment by gabrielreid** [comment]
Ah ok, good to hear, thanks for the workarounds 👍

**Comment by gabrielreid** [comment]
Reopening this because the `opp pr --checkout` doesn't really do what I want.

What I want (for feature parity with competing products in the market) is the equivalent of `opp pr --checkout` and `git reset --hard origin/main` on the base branch just before the checkout of the local branch is done, so just using `--checkout` doesn't cut it.

I'm proposing to add a `--reset` flag to the `pr` command that will do what I want (and so I'll do that unless y'all tell me that this is a terrible idea).

It also makes me wonder: what is the workflow when you've got multiple unrelated PR branches in flight if you're not using this?

**Comment by cupcicm** [comment]
Compared to the tool you are referring to, `opp` has two of differences that make implementing `--reset` harder (and, maybe, less useful ? I don't know. At least, two differences that made me not implement it right away).
1. `opp` makes it possible to create dependent PRs. On your master branch you create 2 commits, push a PR (pr/1) then two more and create pr/2 that depends on pr/1. If you reset `master` to `origin/master` after pushing pr/1 you cannot create pr/2 on top of it easily.
2. `opp` makes it possible to create PRs be carefully selecting what commits go in the PR. For example you can create 3 commits, run `opp pr --interactive` and select just the middle commit to go in a PR. After this, we cannot really reset the main branch because it still contains unpublished commits.

I think we have a few options:
1. forget about my discrepancy comment [here](https://github.com/cupcicm/opp/issues/101#issuecomment-1770191097) and implement reset. After all that's what that other tool was doing. It's sad though, I don't like this discrepancy. Also `--reset` would be incompatible with `--interactive`, and with providing a SHA that's not HEAD.
2. I could try to convince you you don't need it 🤔 . This comment
> what is the workflow when you've got multiple unrelated PR branches in flight if you're not using this?
makes me think maybe I could convince you. I personally have one (or sometimes a few) master branches locally and I keep a history of all commits I have made there. Then I can choose to create either dependent PRs (`opp pr SHA`) or independent PRs (`opp pr --base master SHA`). Master is a good reminder of all the unmerged code I have written, and that sits in multiple PRs. Sometimes, for stuff that's really independent, I `git rebase --interactive origin/master` and delete a few commits that are safely kept in a PR branch.
3. Do it outside opp

```git reset --hard origin/master && git checkout HEAD@{1} && opp pr``` does exactly what you want I think. 


What do you think ? I'll look at your PR too.

**Comment by gabrielreid** [comment]
I might be trying to hard to make this work like the competing tool that we're talking about.

I definitely don't think that my own flow is reason enough to push a discrepancy in though, so I think that invalidates option 1.

Looking at your flow in option 2, I think that's a bridge too far for me to adopt that way of working, at least for now :-) I'm interested in giving it a try, but it's pretty far from how I generally work today.

However, option 3 looks very promising, and it _almost_ does exactly what I want. The one remaining problem is that it seems to leave you on the PR branch (regardless of whether you use `--checkout` or not). I think I can live with that though, so I can just make an alias that does the following if I don't want to have the `--checkout` behavior:
```
git reset --hard origin/master && git checkout HEAD@{1} && opp pr && git checkout origin/master
```

I guess there's also the matter of knowing what the name of the "main" branch is, but I guess my script can figure that out from the branch that it's starting from.

All of that to say, it sounds like just doing this outside opp is the way to go if I want to use the tool in this way. Agree?

**Comment by cupcicm** [comment]
Let me offer you this

``` $ cat > ~/bin/opp-cut-pr.sh
mainbranch=$(git rev-parse --abbrev-ref origin/HEAD | sed s#origin/##)
opp pr && git reset --hard origin/$mainbranch
```

The `mainbranch` variable will hold `main` or `master` or whatever the main branch is.
And `opp pr` without `--checkout` will not checkout the PR branch when you're on a branch (in my previous example, it did, because it's not cool to let you stay on a detached head, but if you're already on a branch, it keeps you there after the PR has been created), and so you can reset the main branch.

I would probably even add a small `git stash &&` before the `opp pr` to not lose some uncommited work sometimes.

**Comment by gabrielreid** [comment]
Yep, that looks like it'll cover it, sounds good. And good call on the git stash as well 👍 

Thanks for that, I'll close this and the PR and make my local alias for this stuff (and I'll at least try giving your workflow a try 😄)
